version: '3'

env:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

tasks:
  default:
    cmds:
    - (cd analytics1d && go build -o ../bin/analytics1d)
    - (cd analytics1w && go build -o ../bin/analytics1w)
    - (cd analytics1m && go build -o ../bin/analytics1m)
