---
version: "3"

includes:
  go:
    taskfile: src/Taskfile.yaml
    dir: src
  localstack:
    taskfile: tasks/localstack.yaml

tasks:
  default:
    silent: true
    cmds:
      - cmd: task --list --sort=none
