---
version: "3"

tasks:
  default:
    cmds:
    - task --sort=none

  init:
    desc: Run `terraform init`
    cmds:
    - terraform init {{.CLI_ARGS}}

  fmt:
    desc: Run `terraform fmt`
    cmds:
    - terraform fmt {{.CLI_ARGS}}

  plan:
    desc: Run `terraform plan`
    cmds:
      - terraform plan {{.CLI_ARGS}}

  apply:
    desc: Run `terraform apply`
    cmds:
      - terraform apply {{.CLI_ARGS}}

  # TODO: upload resources to bucket for viewing charts
  upload_to_code_bucket:
    desc: Uploads zipped binary to the code bucket
    vars:
      ZIPPED_BINARY_PATH: ../src/main.zip
    cmds:
    - >-
      aws
      --profile={{.AWS_PROFILE}}
      s3
      cp
      {{.ZIPPED_BINARY_PATH}}
      s3://{{.CODE_BUCKET_NAME}}/build.zip

  update_lambda_code:
    desc: Upload new binary and re-fresh lambda
    vars:
      FUNCTION_NAME: ac93uk-cloudflare-analytics
    cmds:
    - task: upload_to_code_bucket
    - >-
      aws
      --no-cli-pager
      --profile={{.AWS_PROFILE}}
      lambda
      update-function-configuration
      --function-name="{{.FUNCTION_NAME}}"
